### ISSUE TITLE
Decide how to handle charsets that are not UTF-8

### ISSUE THREAD

**Issue by mipli** [mipli/sgf-parser#11]
Default charset, per the specification, is ISO-8859-1 so we should at least support that encoding properly.

**Comment by SamBlaise** [comment]
The encoding is not handled by pest ? I tried with an sgf and it worked.

**Comment by mipli** [comment]
That's great. Reading works then, but we need to fix writing as well. 

Preferably the library should support producing an ISO-8859-1 string when the charset token indicates that. But I'm not quiet sure how to do that, and if it is too tricky I don't mind forcing all created string to be UTF-8 as long as we update the charset token as well.
