### ISSUE TITLE
Added missing token to is_root_token

### ISSUE THREAD

**Issue by SamBlaise** [mipli/sgf-parser#13]
Due to recent support of new nodes, before 2.2 add missing nodes to is_root_token.
And maybe support 
is_gameinfo_token
is_setup_property
etc..

**Comment by mipli** [comment]
Good point, I'll get that sorted as soon as possible.

**Comment by mipli** [comment]
Started work on this now, progress is here: https://github.com/mipli/sgf-parser/pull/14

Going to add a method to the `GamtTree` to check that a tree is valid as well before merging this.

**Comment by mipli** [comment]
Solved in #14
